version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/new_chatapp
hooks: 
  BeforeInstall:
    - location: /scripts/install_dependencies.sh
      timeout: 100
      runas: root
  AfterInstall:
    - location: /scripts/change_file.sh
      timeout: 100
      runas: root

